### ISSUE TITLE
Production API host doesn't work out of the box

### ISSUE THREAD

**Issue by taddeimania** [taddeimania/django-ember-api-auth-example#1]

**Comment by yanik-ai** [comment]
User `ember server --proxy http://localhost:8000` to point proxy to default Django runserver.

**Comment by taddeimania** [comment]
I meant in a deployed environment for some reason it wanted to use `localhost:8000` for all Ember Data requests.

this is closed by b8383b22b4d4d06b05dd4affcf8d11b369455170
